### ISSUE TITLE
Facing problems while trying to run locally

### ISSUE THREAD

**Issue by hishamcse** [diogoantunes25/Alea-BFT#1]
try to build docker container using: docker build -t alea .

which fails. the error log is attached.
[64.95 [ERROR] COMPILATION ERROR.txt](https://github.com/user-attachments/files/17874838/64.95.ERROR.COMPILATION.ERROR.txt)

Any help will be greatly appreciated. Thanks!

**Comment by diogoantunes25** [comment]
Thank you for reporting this issue and providing the error log. I believe it has now been resolved. Let me know if the issue persists or if you encounter any other problems.
